# Generated by Django 4.2.21 on 2025-06-13 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='challenge',
        ),
    ]
